{
  logger.error("Unexpected Exception happened. event:{}",e,e.getCause());
}
