{
  try {
    listener.onComplete(this);
    return true;
  }
 catch (  Throwable th) {
    logger.warn("FutureListener.onComplete() fail Caused:{}",th.getMessage(),th);
    return false;
  }
}
